apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  labels:
    release.appstudio.openshift.io/automated: "false"
    release.appstudio.openshift.io/automated: "user"
  name: demo-snapshot-test
  namespace: release-1503-dev
spec:
  gracePeriodDays: 7
  releasePlan: 1503-rp
  snapshot: demo-snapshot
