---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  labels:
    release.appstudio.openshift.io/author: kube_admin
  name: no-pipeline-or-target
  namespace: release-1109-dev
spec:
  releasePlan: no-pipeline-or-target
  snapshot: demo-snapshot
