apiVersion: appstudio.redhat.com/v1alpha1
kind: EnterpriseContractPolicy
metadata:
  name: mvp-policy
  namespace: release-1109-managed
spec:
  description: Red Hat's enterprise requirements
  publicKey: |-
    -----BEGIN PUBLIC KEY-----
    MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEVV14494lsRp3JLbZ8DLRtQ+l2/hE
    d5e9tbaLqHD6UKC58K1tEpigzC80K176sjobkI29UjOGJqWo5SOEq835sQ==
    -----END PUBLIC KEY-----
  sources:
    - data:
        - "git::https://github.com/hacbs-contract/ec-policies.git//data"
      name: ec-policies
      policy:
        - "git::https://github.com/hacbs-contract/ec-policies.git//policy"
