---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  labels:
    release.appstudio.openshift.io/author: kube_admin
  name: tenant-pipeline-only
  namespace: release-1109-dev
spec:
  releasePlan: tenant-pipeline-only
  snapshot: demo-snapshot
